language: node_js
node_js:
- '5'

before_install:
- openssl aes-256-cbc -K $encrypted_c3289eabfb80_key -iv $encrypted_c3289eabfb80_iv
  -in secrets.tar.enc -out secrets.tar -d

deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    branch: master
