language: node_js

node_js:
  - '5'

before_install: ./before_install.sh

before_deploy:
  - echo -e "Host girlfriend.wtf\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
