language: node_js

node_js:
  - '5'

before_install:
  - openssl aes-256-cbc -K $encrypted_07aba4ee01ad_key -iv $encrypted_07aba4ee01ad_iv -in deploy.tar.enc -out deploy.tar -d
  - tar xvf deploy.tar
  - chmod u+x deploy.sh

before_script:
  - echo -e "Host girlfriend.wtf\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
